#! /bin/bash

# Shell tests runner.
# Copyright (C) 2017 Red Hat, Inc.
#
# This file is part of resalloc project.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Hack, avoid generating WORKDIR for now
WORKDIR=/tmp
. ./testlib

result=true

export POSTGRESQL_PORT=65432
export SERVER_PORT=55554

for TEST_NAME; do
    SERVER_PORT=$(( SERVER_PORT - 1 ))
    POSTGRESQL_PORT=$(( POSTGRESQL_PORT - 1 ))
    echo "===> running test 'tests/$TEST_NAME' ($PYTHON+$DATABASE)"

    export WORKDIR=$(mktemp -d /tmp/resalloc-tests-$TEST_NAME-XXXXXXX)

    status=OK
    if ! ./tests/"$TEST_NAME" ; then
        status=FAIL
        result=false
    else
        test -d "$WORKDIR" && rm -rf "$WORKDIR"
    fi

    echo "                              ---> [ $status ]"
done

$result

# vi: ft=sh
