#! /bin/bash

# Helper script (used by praiskup atm) to update CI scripting on Copr side.

script=$(readlink -f "$(dirname "$0")")/copr-custom-script

PROJECT=praiskup/resalloc-ci

build_deps=(
    git
    make
    python3-setuptools
    python-unversioned-command
)

copr_cmd=(
    copr edit-package-custom "$PROJECT" \
        --webhook-rebuild on \
        --script "$script" \
        --script-chroot "fedora-latest-x86_64" \
        --script-builddeps "${build_deps[*]}" \
        --max-builds 15 \
)

"${copr_cmd[@]}" --name resalloc --script-resultdir resalloc/rpm
