#! /bin/bash

set -e

# we run this only for pull-requests, pushes are tested separately
# by copr(tito) webhooks
test "$TRAVIS_PULL_REQUEST" = false && exit 0

# download up2date travis trigger
curl -o copr-build https://raw.githubusercontent.com/praiskup/copr-ci-tooling/master/copr-travis-submit

# trigger the build and watch it
export COPR_PR_WEBHOOK="https://copr.fedorainfracloud.org/webhooks/custom/24190/c23f34c1-e02e-41a0-9435-6c7e4a6e56c0/resalloc/"

exec bash copr-build
